# way-displays configuration

# Arrange displays in a ROW (default, left to right) or a COLUMN (top to bottom)
ARRANGE: ROW

# Align ROWs at the TOP (default), MIDDLE or BOTTOM
# Align COLUMNs at the LEFT (default), MIDDLE or RIGHT
ALIGN: TOP


# The default ORDER is simply the order in which the displays are discovered.
# Define your own.
ORDER:
  #- 'DP-2'
  #- 'monitor description'
  #- 'HDMI-1'


# The default is to scale each display by DPI.
# This may be disabled and scale 1 will be used, unless a SCALE has been specified.
AUTO_SCALE: TRUE


# Auto scale may be overridden for each display.
SCALE:
  #- NAME_DESC: 'monitor description'
  #  SCALE: 1.75


# Laptop displays usually start with eDP e.g. eDP-1. This may be overridden if
# your laptop is different.
#LAPTOP_DISPLAY_PREFIX: 'eDP'


# One of: ERROR, WARNING, INFO (default), DEBUG
#LOG_THRESHOLD: INFO
